all:
	g++ experimento_compresion.cpp -o experimento_compresion.out -g
	g++ experimento_decompresion.cpp -o experimento_decompresion.out -g
	g++ experimento_porcentaje.cpp -o experimento_poercentaje.out -g



