all:
	g++ experimento_compresion.cpp -o experimento_compresion.out 
	g++ experimento_porcentaje.cpp -o experimento_porcentaje.out 
	g++ experimento_largo_subcadena_LZ.cpp -o experimento_compresion_LZ.out
	
	g++ experimento_codificacion_huffman_memoria.cpp -o compresion_huffman.out -g
	g++ experimento_decompresion_memoria_huffman.cpp -o descompresion_huffman.out -g
	g++ experimento_compresion_LZ_memoria.cpp -o compresion_lz.out -g
	g++ experimento_decompresion_memoria_LZ.cpp -o descompresion_lz.out -g